/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WritingRouteImport } from './routes/writing'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as NewsletterRouteImport } from './routes/newsletter'
import { Route as ChangelogRouteImport } from './routes/changelog'
import { Route as BugsRouteImport } from './routes/bugs'
import { Route as R404RouteImport } from './routes/404'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LabsIndexRouteImport } from './routes/labs.index'
import { Route as CaseStudiesIndexRouteImport } from './routes/case-studies.index'
import { Route as WritingSlugRouteImport } from './routes/writing.$slug'
import { Route as LabsMcpRouteImport } from './routes/labs.mcp'
import { Route as LabsDecomposerRouteImport } from './routes/labs.decomposer'
import { Route as CaseStudiesDzarvisRouteImport } from './routes/case-studies.dzarvis'

const WritingRoute = WritingRouteImport.update({
  id: '/writing',
  path: '/writing',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsletterRoute = NewsletterRouteImport.update({
  id: '/newsletter',
  path: '/newsletter',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangelogRoute = ChangelogRouteImport.update({
  id: '/changelog',
  path: '/changelog',
  getParentRoute: () => rootRouteImport,
} as any)
const BugsRoute = BugsRouteImport.update({
  id: '/bugs',
  path: '/bugs',
  getParentRoute: () => rootRouteImport,
} as any)
const R404Route = R404RouteImport.update({
  id: '/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LabsIndexRoute = LabsIndexRouteImport.update({
  id: '/labs/',
  path: '/labs/',
  getParentRoute: () => rootRouteImport,
} as any)
const CaseStudiesIndexRoute = CaseStudiesIndexRouteImport.update({
  id: '/case-studies/',
  path: '/case-studies/',
  getParentRoute: () => rootRouteImport,
} as any)
const WritingSlugRoute = WritingSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => WritingRoute,
} as any)
const LabsMcpRoute = LabsMcpRouteImport.update({
  id: '/labs/mcp',
  path: '/labs/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const LabsDecomposerRoute = LabsDecomposerRouteImport.update({
  id: '/labs/decomposer',
  path: '/labs/decomposer',
  getParentRoute: () => rootRouteImport,
} as any)
const CaseStudiesDzarvisRoute = CaseStudiesDzarvisRouteImport.update({
  id: '/case-studies/dzarvis',
  path: '/case-studies/dzarvis',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/404': typeof R404Route
  '/bugs': typeof BugsRoute
  '/changelog': typeof ChangelogRoute
  '/newsletter': typeof NewsletterRoute
  '/projects': typeof ProjectsRoute
  '/writing': typeof WritingRouteWithChildren
  '/case-studies/dzarvis': typeof CaseStudiesDzarvisRoute
  '/labs/decomposer': typeof LabsDecomposerRoute
  '/labs/mcp': typeof LabsMcpRoute
  '/writing/$slug': typeof WritingSlugRoute
  '/case-studies/': typeof CaseStudiesIndexRoute
  '/labs/': typeof LabsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/404': typeof R404Route
  '/bugs': typeof BugsRoute
  '/changelog': typeof ChangelogRoute
  '/newsletter': typeof NewsletterRoute
  '/projects': typeof ProjectsRoute
  '/writing': typeof WritingRouteWithChildren
  '/case-studies/dzarvis': typeof CaseStudiesDzarvisRoute
  '/labs/decomposer': typeof LabsDecomposerRoute
  '/labs/mcp': typeof LabsMcpRoute
  '/writing/$slug': typeof WritingSlugRoute
  '/case-studies': typeof CaseStudiesIndexRoute
  '/labs': typeof LabsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/404': typeof R404Route
  '/bugs': typeof BugsRoute
  '/changelog': typeof ChangelogRoute
  '/newsletter': typeof NewsletterRoute
  '/projects': typeof ProjectsRoute
  '/writing': typeof WritingRouteWithChildren
  '/case-studies/dzarvis': typeof CaseStudiesDzarvisRoute
  '/labs/decomposer': typeof LabsDecomposerRoute
  '/labs/mcp': typeof LabsMcpRoute
  '/writing/$slug': typeof WritingSlugRoute
  '/case-studies/': typeof CaseStudiesIndexRoute
  '/labs/': typeof LabsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/404'
    | '/bugs'
    | '/changelog'
    | '/newsletter'
    | '/projects'
    | '/writing'
    | '/case-studies/dzarvis'
    | '/labs/decomposer'
    | '/labs/mcp'
    | '/writing/$slug'
    | '/case-studies/'
    | '/labs/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/404'
    | '/bugs'
    | '/changelog'
    | '/newsletter'
    | '/projects'
    | '/writing'
    | '/case-studies/dzarvis'
    | '/labs/decomposer'
    | '/labs/mcp'
    | '/writing/$slug'
    | '/case-studies'
    | '/labs'
  id:
    | '__root__'
    | '/'
    | '/404'
    | '/bugs'
    | '/changelog'
    | '/newsletter'
    | '/projects'
    | '/writing'
    | '/case-studies/dzarvis'
    | '/labs/decomposer'
    | '/labs/mcp'
    | '/writing/$slug'
    | '/case-studies/'
    | '/labs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  R404Route: typeof R404Route
  BugsRoute: typeof BugsRoute
  ChangelogRoute: typeof ChangelogRoute
  NewsletterRoute: typeof NewsletterRoute
  ProjectsRoute: typeof ProjectsRoute
  WritingRoute: typeof WritingRouteWithChildren
  CaseStudiesDzarvisRoute: typeof CaseStudiesDzarvisRoute
  LabsDecomposerRoute: typeof LabsDecomposerRoute
  LabsMcpRoute: typeof LabsMcpRoute
  CaseStudiesIndexRoute: typeof CaseStudiesIndexRoute
  LabsIndexRoute: typeof LabsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/writing': {
      id: '/writing'
      path: '/writing'
      fullPath: '/writing'
      preLoaderRoute: typeof WritingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/newsletter': {
      id: '/newsletter'
      path: '/newsletter'
      fullPath: '/newsletter'
      preLoaderRoute: typeof NewsletterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/changelog': {
      id: '/changelog'
      path: '/changelog'
      fullPath: '/changelog'
      preLoaderRoute: typeof ChangelogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bugs': {
      id: '/bugs'
      path: '/bugs'
      fullPath: '/bugs'
      preLoaderRoute: typeof BugsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/404': {
      id: '/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof R404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/labs/': {
      id: '/labs/'
      path: '/labs'
      fullPath: '/labs/'
      preLoaderRoute: typeof LabsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/case-studies/': {
      id: '/case-studies/'
      path: '/case-studies'
      fullPath: '/case-studies/'
      preLoaderRoute: typeof CaseStudiesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/writing/$slug': {
      id: '/writing/$slug'
      path: '/$slug'
      fullPath: '/writing/$slug'
      preLoaderRoute: typeof WritingSlugRouteImport
      parentRoute: typeof WritingRoute
    }
    '/labs/mcp': {
      id: '/labs/mcp'
      path: '/labs/mcp'
      fullPath: '/labs/mcp'
      preLoaderRoute: typeof LabsMcpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/labs/decomposer': {
      id: '/labs/decomposer'
      path: '/labs/decomposer'
      fullPath: '/labs/decomposer'
      preLoaderRoute: typeof LabsDecomposerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/case-studies/dzarvis': {
      id: '/case-studies/dzarvis'
      path: '/case-studies/dzarvis'
      fullPath: '/case-studies/dzarvis'
      preLoaderRoute: typeof CaseStudiesDzarvisRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface WritingRouteChildren {
  WritingSlugRoute: typeof WritingSlugRoute
}

const WritingRouteChildren: WritingRouteChildren = {
  WritingSlugRoute: WritingSlugRoute,
}

const WritingRouteWithChildren =
  WritingRoute._addFileChildren(WritingRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  R404Route: R404Route,
  BugsRoute: BugsRoute,
  ChangelogRoute: ChangelogRoute,
  NewsletterRoute: NewsletterRoute,
  ProjectsRoute: ProjectsRoute,
  WritingRoute: WritingRouteWithChildren,
  CaseStudiesDzarvisRoute: CaseStudiesDzarvisRoute,
  LabsDecomposerRoute: LabsDecomposerRoute,
  LabsMcpRoute: LabsMcpRoute,
  CaseStudiesIndexRoute: CaseStudiesIndexRoute,
  LabsIndexRoute: LabsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
